// Hub blocklist for No-Hub Challenge mode
// Prevents players from navigating to major Wikipedia hub pages

export const HUB_PAGES = new Set([
  // Continents & regions
  'Africa',
  'Asia',
  'Europe',
  'North America',
  'South America',
  'Oceania',
  'Antarctica',
  'Middle East',
  'Southeast Asia',
  'Central Asia',
  'East Asia',
  'South Asia',
  'West Africa',
  'Eastern Europe',
  'Western Europe',
  'Latin America',
  'Caribbean',

  // Major countries (50+)
  'United States',
  'United Kingdom',
  'Germany',
  'France',
  'Russia',
  'China',
  'India',
  'Japan',
  'Italy',
  'Spain',
  'Canada',
  'Australia',
  'Brazil',
  'Mexico',
  'Poland',
  'Netherlands',
  'Sweden',
  'Norway',
  'Denmark',
  'Finland',
  'Switzerland',
  'Austria',
  'Belgium',
  'Portugal',
  'Greece',
  'Turkey',
  'Israel',
  'Iran',
  'Iraq',
  'Egypt',
  'South Africa',
  'Argentina',
  'Colombia',
  'Chile',
  'Pakistan',
  'Bangladesh',
  'Nigeria',
  'Indonesia',
  'South Korea',
  'North Korea',
  'Vietnam',
  'Thailand',
  'Philippines',
  'Saudi Arabia',
  'Ukraine',
  'Romania',
  'Hungary',
  'Czech Republic',
  'Serbia',
  'Croatia',
  'Kenya',
  'Malaysia',

  // Years (critical for historical searches)
  '1900',
  '1901',
  '1910',
  '1914',
  '1915',
  '1916',
  '1917',
  '1918',
  '1919',
  '1920',
  '1930',
  '1933',
  '1939',
  '1940',
  '1941',
  '1942',
  '1943',
  '1944',
  '1945',
  '1946',
  '1950',
  '1960',
  '1970',
  '1980',
  '1989',
  '1990',
  '1991',
  '2000',
  '2001',
  '2003',
  '2008',
  '2010',
  '2020',

  // Wikipedia mega-hubs (major topics with massive link networks)
  'World War I',
  'World War II',
  'Cold War',
  'Holocaust',
  'Nazi Germany',
  'Adolf Hitler',
  'English language',
  'Latin',
  'French language',
  'German language',
  'Spanish language',
  'Christianity',
  'Islam',
  'Judaism',
  'Catholicism',
  'Protestant Reformation',
  'Roman Empire',
  'Roman Catholic Church',
  'British Empire',
  'Soviet Union',
  'United Nations',
  'European Union',
  'NATO',
  'Olympic Games',
  'Nobel Prize',
  'Academy Award',
  'Grammy Award',
  'Wikipedia',
  'Encyclopedia',
  'Biology',
  'Chemistry',
  'Physics',
  'Mathematics',
  'History',
  'Geography',
  'Philosophy',
  'Economics',
  'Politics',

  // Major cities
  'New York City',
  'London',
  'Paris',
  'Berlin',
  'Rome',
  'Tokyo',
  'Beijing',
  'Moscow',
  'Los Angeles',
  'Chicago',
  'Sydney',
  'Toronto',
  'Madrid',
  'Vienna',
  'Amsterdam',
  'Brussels',
  'Warsaw',
  'Budapest',
  'Prague',
  'Athens',

  // Other major hubs
  'President of the United States',
  'Prime Minister of the United Kingdom',
  'Democratic Party (United States)',
  'Republican Party (United States)',
  'Communist Party of China',
  'University',
  'Harvard University',
  'Oxford University',
  'Cambridge University',
  'List of countries by population',
  'List of countries by area',
  'Wikipedia portal',
  'Portal (Wikipedia)',
  'Category (Wikipedia)',
])

// Derived lowercase set for O(1) hub page lookups
const HUB_PAGES_LOWER = new Set(Array.from(HUB_PAGES).map(h => h.toLowerCase()))

export function isHubPage(title) {
  if (!title || typeof title !== 'string') return false
  return HUB_PAGES_LOWER.has(title.trim().toLowerCase())
}
